# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f26ffd90514c26ea4d49b63bfce4d873fd9e0573e3a926a2cbf6500bbf42772c9bab4dd137f248f4e973c5f04c5ec848a23a145c9312afbdedda9e004970f9

test:
  secret_key_base: 30352d71dbc05db8a2338b72c75f3a3e1803860c1763714745753ed7cd00b4ff2ebd9fcddd59998247262afec2860c91adbf185942f4bc86c1c152208ae06afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
